#!/usr/bin/env bash
# Configures nginx to add a custom HTTP response header

apt-get update
apt-get install -y nginx

sed -i '/server_name _;/a \
add_header X-Served-By $hostname;\n' /etc/nginx/sites-available/default

service nginx start
