#!/usr/bin/env bash
# Install Nginx web server

# Update package list
apt-get update -y

# Install nginx
apt-get install -y nginx

# Allow HTTP traffic
ufw allow 'Nginx HTTP'

# Start nginx (NOT systemctl)
service nginx start

# Create required page
echo "Holberton School for the win!" > /var/www/html/index.nginx-debian.html

