#!/usr/bin/env bash
# This script installs nginx and sets up the default page for Holberton School

# Update packages
apt-get update -y

# Install nginx
apt-get install -y nginx

# Start nginx (do not use systemctl)
service nginx start

# Make sure nginx listens on port 80
ufw allow 'Nginx HTTP'

# Create the default page
echo "Holberton School for the win!" > /var/www/html/index.nginx-debian.html

# Fix permissions
chown www-data:www-data /var/www/html/index.nginx-debian.html
chmod 644 /var/www/html/index.nginx-debian.html

