#!/usr/bin/env bash

apt-get update -y
apt-get install nginx -y

# Create index page
echo "Holberton School for the win!" > /var/www/html/index.html

# Configure redirect
sed -i '/server_name _;/a \
location /redirect_me {\
    return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\
}' /etc/nginx/sites-available/default

service nginx restart
