#!/usr/bin/env bash
# Configures nginx redirection

apt-get update -y
apt-get install nginx -y

sed -i '/listen 80 default_server;/a \
    location /redirect_me {\n\
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\
    }\n' /etc/nginx/sites-available/default

service nginx restart
