#!/usr/bin/env bash
# Configures a custom 404 error page

apt-get update -y
apt-get install nginx -y

echo "Ceci n'est pas une page" > /var/www/html/404.html

sed -i '/server_name _;/a \
    error_page 404 /404.html;\n\
    location = /404.html {\n\
        internal;\n\
    }\n' /etc/nginx/sites-available/default

service nginx restart

