#!/usr/bin/env bash

apt-get update -y
apt-get install nginx -y

# Main page
echo "Holberton School for the win!" > /var/www/html/index.html

# 404 page
echo "Ceci n'est pas une page" > /var/www/html/404.html

# Nginx config
sed -i '/server_name _;/a \
error_page 404 /404.html;\
location = /404.html {\
    internal;\
}' /etc/nginx/sites-available/default

service nginx restart
